name: CI - testing
# run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
      # Add "id-token" with the intended permissions.
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/798532658065/locations/global/workloadIdentityPools/github/providers/github-action'
        service_account: 'bqport-testing@takegue.iam.gserviceaccount.com'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
    - run: npm ci
    - run: npm run build --if-present
    - shell:
        # Force allocate TTY on GitHub Action: https://github.com/actions/runner/issues/241
        'script -q -e -c "bash --noprofile --norc -eo pipefail {0}"'
      run: npm test
